!Panoptica_Evaluator
decision_metric: null
decision_threshold: null
edge_case_handler: !EdgeCaseHandler
  empty_list_std: !EdgeCaseResult NAN
  listmetric_zeroTP_handling:
    !Metric DSC: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult ZERO,
      empty_reference_result: !EdgeCaseResult ZERO, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult ZERO}
    !Metric clDSC: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult ZERO,
      empty_reference_result: !EdgeCaseResult ZERO, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult ZERO}
    !Metric IOU: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult ZERO,
      empty_reference_result: !EdgeCaseResult ZERO, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult ZERO}
    !Metric ASSD: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult INF,
      empty_reference_result: !EdgeCaseResult INF, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult INF}
    !Metric RVD: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult NAN,
      empty_reference_result: !EdgeCaseResult NAN, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult NAN}
instance_metrics: [!Metric DSC, !Metric IOU, !Metric ASSD, !Metric RVD]
global_metrics: [!Metric DSC, !Metric RVD, !Metric IOU]
expected_input: !InputType UNMATCHED_INSTANCE
instance_approximator: null
instance_matcher: !NaiveThresholdMatching {allow_many_to_one: false, matching_metric: !Metric IOU,
  matching_threshold: 0.5}
log_times: false
segmentation_class_groups: !SegmentationClassGroups
  groups:
    vertebra: !LabelGroup
      single_instance: false
      value_labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
verbose: false
